// <auto-generated />
using System;
using IronMan.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IronMan.Data.Migrations
{
    [DbContext(typeof(IronManDbContext))]
    partial class IronManDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IronMan.Data.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Activated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Verified")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DeleterId");

                    b.HasIndex("LastModifierUserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activated = new DateTime(2024, 3, 8, 15, 36, 20, 844, DateTimeKind.Unspecified).AddTicks(7440),
                            Created = new DateTime(2024, 3, 8, 15, 36, 20, 844, DateTimeKind.Unspecified).AddTicks(9570),
                            CreationTime = new DateTime(2024, 3, 8, 17, 36, 20, 838, DateTimeKind.Unspecified).AddTicks(6430),
                            Email = "Franklin@shearwatervf.com",
                            FirstName = "Franklin",
                            IsDeleted = false,
                            LastName = "Ndlovu",
                            PasswordHash = "$2a$11$xccdiOHYF6NCiwv05bTS6OmBTebIXrq9YCHJpOTdUwnJ9D6rrdy7i",
                            PasswordReset = new DateTime(2024, 4, 17, 13, 38, 20, 888, DateTimeKind.Unspecified).AddTicks(5144),
                            Role = 0,
                            Title = "Mr",
                            Verified = new DateTime(2024, 3, 8, 15, 38, 20, 275, DateTimeKind.Unspecified).AddTicks(850)
                        },
                        new
                        {
                            Id = 2,
                            Activated = new DateTime(2024, 3, 8, 15, 41, 5, 580, DateTimeKind.Unspecified).AddTicks(7190),
                            Created = new DateTime(2024, 3, 8, 15, 40, 30, 575, DateTimeKind.Unspecified).AddTicks(1440),
                            CreationTime = new DateTime(2024, 3, 8, 17, 40, 30, 521, DateTimeKind.Unspecified).AddTicks(8190),
                            Email = "evstores@shearwatervf.com",
                            FirstName = "Batirai A. A.",
                            IsDeleted = false,
                            LastName = "Rutsito",
                            PasswordHash = "$2a$11$x1fZNHZb56UDOT6G50O/Y.g8GcHo7lQ/voCe6DoBpAp55bLwjoD4S",
                            Role = 1,
                            Title = "Mr",
                            Verified = new DateTime(2024, 3, 8, 15, 40, 46, 380, DateTimeKind.Unspecified).AddTicks(1770)
                        },
                        new
                        {
                            Id = 3,
                            Activated = new DateTime(2024, 3, 8, 15, 41, 5, 580, DateTimeKind.Unspecified).AddTicks(7190),
                            Created = new DateTime(2024, 3, 8, 15, 40, 30, 575, DateTimeKind.Unspecified).AddTicks(1440),
                            CreationTime = new DateTime(2024, 3, 8, 17, 40, 30, 521, DateTimeKind.Unspecified).AddTicks(8190),
                            Email = "dought@shearwatervf.com",
                            FirstName = "Dought",
                            IsDeleted = false,
                            LastName = "Tabona",
                            PasswordHash = "$2a$11$x1fZNHZb56UDOT6G50O/Y.g8GcHo7lQ/voCe6DoBpAp55bLwjoD4S",
                            Role = 2,
                            Title = "Mr",
                            Verified = new DateTime(2024, 3, 8, 15, 40, 46, 380, DateTimeKind.Unspecified).AddTicks(1770)
                        },
                        new
                        {
                            Id = 4,
                            Activated = new DateTime(2024, 3, 8, 15, 41, 5, 580, DateTimeKind.Unspecified).AddTicks(7190),
                            Created = new DateTime(2024, 3, 8, 15, 40, 30, 575, DateTimeKind.Unspecified).AddTicks(1440),
                            CreationTime = new DateTime(2024, 3, 8, 17, 40, 30, 521, DateTimeKind.Unspecified).AddTicks(8190),
                            Email = "lawrence@shearwatervf.com",
                            FirstName = "Lawrence",
                            IsDeleted = false,
                            LastName = "Gundo",
                            PasswordHash = "$2a$11$x1fZNHZb56UDOT6G50O/Y.g8GcHo7lQ/voCe6DoBpAp55bLwjoD4S",
                            Role = 2,
                            Title = "Mr",
                            Verified = new DateTime(2024, 3, 8, 15, 40, 46, 380, DateTimeKind.Unspecified).AddTicks(1770)
                        },
                        new
                        {
                            Id = 5,
                            Activated = new DateTime(2024, 3, 8, 15, 41, 5, 580, DateTimeKind.Unspecified).AddTicks(7190),
                            Created = new DateTime(2024, 3, 8, 15, 40, 30, 575, DateTimeKind.Unspecified).AddTicks(1440),
                            CreationTime = new DateTime(2024, 3, 8, 17, 40, 30, 521, DateTimeKind.Unspecified).AddTicks(8190),
                            Email = "antony@shearwatervf.com",
                            FirstName = "Antony",
                            IsDeleted = false,
                            LastName = "Shumba",
                            PasswordHash = "$2a$11$x1fZNHZb56UDOT6G50O/Y.g8GcHo7lQ/voCe6DoBpAp55bLwjoD4S",
                            Role = 2,
                            Title = "Mr",
                            Verified = new DateTime(2024, 3, 8, 15, 40, 46, 380, DateTimeKind.Unspecified).AddTicks(1770)
                        },
                        new
                        {
                            Id = 6,
                            Activated = new DateTime(2024, 4, 12, 15, 19, 53, 900, DateTimeKind.Unspecified).AddTicks(6273),
                            Created = new DateTime(2024, 4, 12, 15, 14, 46, 134, DateTimeKind.Unspecified).AddTicks(5649),
                            CreationTime = new DateTime(2024, 4, 12, 15, 19, 53, 900, DateTimeKind.Unspecified).AddTicks(7119),
                            Email = "irene@shearwatervf.com",
                            FirstName = "Irene",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2024, 4, 12, 15, 19, 53, 900, DateTimeKind.Unspecified).AddTicks(7964),
                            LastName = "Manyowa",
                            PasswordHash = "$2a$11$UjbDIp23q1XIJDkUXYT7peF.9bhReAzR0/is3WRaoHUsSy2Bz86o6",
                            Role = 1,
                            Title = "Ms",
                            Verified = new DateTime(2024, 3, 8, 15, 40, 46, 380, DateTimeKind.Unspecified).AddTicks(1770)
                        },
                        new
                        {
                            Id = 7,
                            Activated = new DateTime(2024, 4, 20, 15, 50, 43, 216, DateTimeKind.Unspecified).AddTicks(6667),
                            Created = new DateTime(2024, 4, 20, 15, 50, 43, 216, DateTimeKind.Unspecified).AddTicks(6667),
                            CreationTime = new DateTime(2024, 4, 20, 15, 50, 43, 216, DateTimeKind.Unspecified).AddTicks(6667),
                            Email = "robert@shearwatervf.com",
                            FirstName = "Robert",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2024, 4, 20, 15, 50, 43, 216, DateTimeKind.Unspecified).AddTicks(6667),
                            LastName = "Gororo",
                            PasswordHash = "$2a$11$x1fZNHZb56UDOT6G50O/Y.g8GcHo7lQ/voCe6DoBpAp55bLwjoD4S",
                            Role = 2,
                            Title = "Mr",
                            Updated = new DateTime(2024, 4, 20, 15, 50, 43, 216, DateTimeKind.Unspecified).AddTicks(6667),
                            Verified = new DateTime(2024, 4, 20, 15, 50, 43, 216, DateTimeKind.Unspecified).AddTicks(6667)
                        },
                        new
                        {
                            Id = 8,
                            Activated = new DateTime(2024, 4, 20, 15, 54, 40, 323, DateTimeKind.Unspecified).AddTicks(3333),
                            Created = new DateTime(2024, 4, 20, 15, 54, 40, 323, DateTimeKind.Unspecified).AddTicks(3333),
                            CreationTime = new DateTime(2024, 4, 20, 15, 54, 40, 323, DateTimeKind.Unspecified).AddTicks(3333),
                            Email = "explorerscafe@shearwatervf.com",
                            FirstName = "Antony",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2024, 4, 20, 15, 54, 40, 323, DateTimeKind.Unspecified).AddTicks(3333),
                            LastName = "Shumba",
                            PasswordHash = "$2a$11$x1fZNHZb56UDOT6G50O/Y.g8GcHo7lQ/voCe6DoBpAp55bLwjoD4S",
                            Role = 2,
                            Title = "Mr",
                            Updated = new DateTime(2024, 4, 20, 15, 54, 40, 323, DateTimeKind.Unspecified).AddTicks(3333),
                            Verified = new DateTime(2024, 4, 20, 15, 54, 40, 323, DateTimeKind.Unspecified).AddTicks(3333)
                        },
                        new
                        {
                            Id = 10,
                            Activated = new DateTime(2024, 4, 23, 8, 36, 33, 586, DateTimeKind.Unspecified).AddTicks(7408),
                            Created = new DateTime(2024, 4, 23, 8, 32, 44, 700, DateTimeKind.Unspecified).AddTicks(2283),
                            CreationTime = new DateTime(2024, 4, 23, 8, 36, 33, 586, DateTimeKind.Unspecified).AddTicks(8274),
                            Email = "mthokozisi@shearwatervf.com",
                            FirstName = "Mthokozisi",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2024, 4, 23, 8, 36, 33, 586, DateTimeKind.Unspecified).AddTicks(9155),
                            LastName = "Nkomazana",
                            PasswordHash = "$2a$11$DgdQk6BZdT5Eg9xCpHdZsu9aTmKh2GLlITWPOYFx7I7BViOdaFKCK",
                            Role = 1,
                            Title = "Mr",
                            Verified = new DateTime(2024, 4, 23, 8, 36, 33, 586, DateTimeKind.Unspecified).AddTicks(7408)
                        },
                        new
                        {
                            Id = 11,
                            Activated = new DateTime(2024, 4, 24, 8, 59, 3, 676, DateTimeKind.Unspecified).AddTicks(1502),
                            Created = new DateTime(2024, 4, 24, 8, 58, 23, 696, DateTimeKind.Unspecified).AddTicks(5660),
                            CreationTime = new DateTime(2024, 4, 24, 8, 59, 3, 676, DateTimeKind.Unspecified).AddTicks(1519),
                            Email = "solomon@shearwatervf.com",
                            FirstName = "Solomon",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2024, 4, 24, 8, 59, 3, 676, DateTimeKind.Unspecified).AddTicks(1522),
                            LastName = "Sai",
                            PasswordHash = "$2a$11$dTkS7icWQ6lf05qeqfGWOu5ARGNyhBGdRGTNVlJWNriP2PjdKnsNS",
                            Role = 1,
                            Title = "Mr",
                            Verified = new DateTime(2024, 4, 24, 8, 59, 3, 676, DateTimeKind.Unspecified).AddTicks(1502)
                        });
                });

            modelBuilder.Entity("IronMan.Data.Entities.Account", b =>
                {
                    b.HasOne("IronMan.Data.Entities.Account", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IronMan.Data.Entities.Account", "Deleter")
                        .WithMany()
                        .HasForeignKey("DeleterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IronMan.Data.Entities.Account", "LastModifierUser")
                        .WithMany()
                        .HasForeignKey("LastModifierUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("IronMan.Data.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedByIp")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ReasonRevoked")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("User")
                                .HasForeignKey("UserId");

                            b1.Navigation("User");
                        });

                    b.Navigation("Creator");

                    b.Navigation("Deleter");

                    b.Navigation("LastModifierUser");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
